services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      PRODUCTION: ${PRODUCTION:-0}
      SECRET_KEY:
      DATABASE_NAME:
      DATABASE_USER:
      DATABASE_PASSWORD:
      DATABASE_HOST:
      DATABASE_PORT: 5432
      EMAIL_HOST_USER:
      EMAIL_HOST_PASSWORD:
      FRONTEND_URL:
      HOST_URL:
      OPENAI_API_KEY:
      ASTRA_DB_APPLICATION_TOKEN:
      ASTRA_DB_API_ENDPOINT:
      REDIS_HOST: redis-service
      REDIS_PORT: 6379
    networks:
      - app-network
    depends_on:
      redis-service:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        VITE_BACKEND_API_URL: ${HOST_URL}
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  redis-service:
    image: redis:6.2-alpine
    x-defang-redis: true
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  database-service:
    image: postgres:13-slim
    x-defang-postgres: true
    environment:
      POSTGRES_PASSWORD:
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app-network:
    driver: bridge