services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    environment:
      PRODUCTION: ${PRODUCTION:-0}
      SECRET_KEY:
      DATABASE_NAME:
      DATABASE_USER:
      DATABASE_PASSWORD:
      DATABASE_HOST:
      DATABASE_PORT: 5432
      EMAIL_HOST_USER:
      EMAIL_HOST_PASSWORD:
      FRONTEND_URL:
      HOST_DOMAIN: backend
      OPENAI_API_KEY:
      ASTRA_DB_APPLICATION_TOKEN:
      ASTRA_DB_API_ENDPOINT:
      REDIS_HOST: redis-service
      REDIS_PORT: 6379
      REDIS_URL: redis://redis-service:6379
    networks:
      - default
    depends_on:
      redis-service:
        condition: service_healthy
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 3gb
        reservations:
          cpus: '0.5'
          memory: 512MiB
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://0.0.0.0:8000/')"]
      interval: 20s
      timeout: 10s
      retries: 3
    # Enable volumes for development only
    volumes:
     - "./backend:/app"

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    # Enable volumes for development only
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - default
    depends_on:
      backend:
        condition: service_healthy

  redis-service:
    image: redis:6.2-alpine
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  default:
    # driver: bridge