converse_with_user:
  description: >
    You are to answer all the users  especially the ones on real estate
    Current user_message = {new_message}
    Answer them having the following context of their conversation as:
    {history}
  expected_output: >
    A response to the user in a respectful and helpful tone
    A concise response to the user's question containing only the final answer.
    Do not show any internal thoughts or reasoning process.
    Structure: Final Answer: [your response here]
  agent: conversation_agent
