# Generated by Django 5.2.1 on 2025-05-17 20:41

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(default=chat.models.generate_alphanumeric_id, max_length=255, unique=True),
        ),
    ]
