# Generated by Django 5.2.1 on 2025-05-29 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('details_url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('bedroom', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, null=True)),
                ('listing_time', models.DateTimeField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('initiator', models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('check_frequency', models.CharField(choices=[('none', 'Do not auto-check'), ('6h', 'Every 6 hours'), ('12h', 'Every 12 hours'), ('24h', 'Every day'), ('72h', 'Every 3 days'), ('7d', 'Every week')], default='none', max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='favorite_property.propertysnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'check_frequency'], name='favorite_pr_user_id_9bf97d_idx'), models.Index(fields=['property'], name='favorite_pr_propert_1c3264_idx')],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
